-- Table: AUTH_METHOD
DROP TABLE IF EXISTS AUTH_METHOD;
CREATE TABLE AUTH_METHOD (UID NUMERIC (16) NOT NULL REFERENCES USERS (UID), KSID NUMERIC (16) NOT NULL REFERENCES KEY_SETS (KSID), Description TEXT NOT NULL, Number_of_keys INTEGER, WindowsPassword TEXT, Hash TEXT NOT NULL);

-- Table: KEY_SETS
DROP TABLE IF EXISTS KEY_SETS;
CREATE TABLE KEY_SETS (KSID NUMERIC (16) PRIMARY KEY UNIQUE NOT NULL, K1 NUMERIC (16), K2 NUMERIC (16), K3 NUMERIC (16), K4 NUMERIC (16), K5 NUMERIC (16), Hash TEXT NOT NULL);

-- Table: KEYS
DROP TABLE IF EXISTS KEYS;
CREATE TABLE KEYS (KID NUMERIC (16) PRIMARY KEY UNIQUE NOT NULL, Description TEXT NOT NULL, Inverted BOOLEAN NOT NULL, Type TEXT NOT NULL, Serial TEXT, Password TEXT, Data TEXT, Hash TEXT NOT NULL);

-- Table: LOGIN_ATTEMPTS
DROP TABLE IF EXISTS LOGIN_ATTEMPTS;
CREATE TABLE LOGIN_ATTEMPTS (UID NUMERIC (16) NOT NULL, User TEXT NOT NULL, Keys TEXT NOT NULL, Time DATETIME NOT NULL, Success BOOLEAN NOT NULL, Hash TEXT NOT NULL);

-- Table: USERS
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (UID NUMERIC (16) PRIMARY KEY NOT NULL UNIQUE, Name STRING (128) NOT NULL UNIQUE, Hash TEXT NOT NULL);
